version: "2"

run:
  concurrency: 2

  timeout: 5m

  # Fail if the error was met.
  issues-exit-code: 1

  # This is very important, bugs in tests are not acceptable either.
  tests: true

  # In most cases this can be empty but there is a popular pattern
  # to keep integration tests under this tag.
  build-tags:
    - unit
    - generate_doc
    - generate_golden

  # With the read-only mode linter will fail if go.mod file is outdated.
  modules-download-mode: readonly

  allow-parallel-runners: false

  # Keep this empty to use the Go version from the go.mod file.
  go: ""

linters:
  enable:
    - asasalint # checks for pass []any as any in variadic func(...any)
    - asciicheck # checks that your code does not contain non-ASCII identifiers
    - bidichk # checks for dangerous unicode character sequences
    - bodyclose # checks whether HTTP response body is closed successfully
    - canonicalheader # checks whether net/http.Header uses canonical header
    - copyloopvar # detects places where loop variables are copied (Go 1.22+)
    - dupl # tool for code clone detection
    - durationcheck # checks for two durations multiplied together
    - embeddedstructfieldcheck # checks embedded types in structs
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - errname # checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error
    - errorlint # finds code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - exptostd # detects functions from golang.org/x/exp/ that can be replaced by std functions
    - fatcontext # detects nested contexts in loops
    - gochecksumtype # checks exhaustiveness on Go "sum types"
    - gocritic # provides diagnostics that check for bugs, performance and style issues
    - godoclint # checks Golang's documentation practice
    - gomoddirectives # manages the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - goprintffuncname # checks that printf-like functions are named with f at the end
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - iface # checks the incorrect use of interfaces, helping developers avoid interface pollution
    - ineffassign # detects when assignments to existing variables are not used
    - intrange # finds places where for loops could make use of an integer range
    - iotamixing # checks if iotas are being used in const blocks with other non-iota declarations
    - loggercheck # checks key value pairs for common logger libraries (kitlog,klog,logr,zap)
    - makezero # finds slice declarations with non-zero initial length
    - mirror # reports wrong mirror patterns of bytes/strings usage
    - modernize # suggests simplifications to Go code, using modern language and library features
    - musttag # enforces field tags in (un)marshaled structs
    - nilerr # finds the code that returns nil even if it checks that the error is not nil
    - nilnesserr # reports that it checks for err != nil, but it returns a different nil value error (powered by nilness and nilerr)
    - nolintlint # reports ill-formed or insufficient nolint directives
    - nosprintfhostport # checks for misuse of Sprintf to construct a host with port in a URL
    - perfsprint # checks that fmt.Sprintf can be replaced with a faster alternative
    - predeclared # finds code that shadows one of Go's predeclared identifiers
    - reassign # checks that package variables are not reassigned
    - rowserrcheck # checks whether Err of rows is checked successfully
    - sloglint # ensure consistent code style when using log/slog
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
    - testableexamples # checks if examples are testable (have an expected output)
    - testifylint # checks usage of github.com/stretchr/testify
    - testpackage # makes you use a separate _test package
    - tparallel # detects inappropriate usage of t.Parallel() method in your Go test codes
    - unconvert # removes unnecessary type conversions
    - unparam # reports unused function parameters
    - unused # checks for unused constants, variables, functions and types
    - usestdlibvars # detects the possibility to use variables/constants from the Go standard library
    - usetesting # reports uses of functions with replacement inside the testing package
    - wastedassign # finds wasted assignment statements
    - whitespace # detects leading and trailing whitespace
    - tagalign # checks that struct tags are well aligned    

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - ifElseChain
        - unlambda
        - singleCaseSwitch

    errcheck:
      # Report `a := b.(MyStruct)` when `a, ok := ...` should be.
      check-type-assertions: true # Default: false

      # Report skipped checks:`num, _ := strconv.Atoi(numStr)`.
      check-blank: false # Default: false
      
      # Functions to skip.
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - (*github.com/fatih/color.Color).Fprintf
        - (*github.com/fatih/color.Color).Fprintln
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint

    staticcheck:
      checks:
        - "all"
        - "-SA9003"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-ST1023"
        - "-ST1005"

    govet:
      settings:
        printf:
          funcs:
            - (github.com/pjkaufman/go-go-gadgets/pkg/loggger).WriteInfof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).WriteWarnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).WriteErrorf

  exclusions:
    rules:
      # the following paths both have a lot of duplicate test data and that is fine
      - path: '(.+)(handle-validation-errors|validation-errors-sort)_test\.go'
        linters:
          - dupl 

issues:
  # Setting to 0 to have all the results.
  max-issues-per-linter: 0

  # Same here, nothing should be skipped to not miss errors.
  max-same-issues: 0

  # Look at all of the code
  new: false
  
  # I will decide when things need fixing
  fix: false