# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: cat-ascii
    main: ./cat-ascii/main.go
    binary: cat-ascii
    goos:
      - linux
      - darwin
      - windows

  - id: epub-lint
    main: ./epub-lint/main.go
    binary: epub-lint
    goos:
      - linux
      - darwin
      - windows

  - id: jp-proc
    main: ./jp-proc/main.go
    binary: jp-proc
    goos:
      - linux
      - darwin
      - windows

  - id: magnum
    main: ./magnum/main.go
    binary: magnum
    goos:
      - linux
      - darwin
      - windows

  - id: song-converter
    main: ./song-converter/main.go
    binary: song-converter
    goos:
      - linux
      - darwin
      - windows

  - id: versy
    main: ./versy/main.go
    binary: versy
    goos:
      - linux
      - darwin
      - windows

archives:
  # cat-ascii binary only
  - id: cat-ascii-archive
    ids:
      - cat-ascii
    formats: binary
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # epub-lint binary only
  - id: epub-lint-archive
    ids:
      - epub-lint
    formats: binary
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # jp-proc binary only
  - id: jp-proc-archive
    ids:
      - jp-proc
    formats: binary
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # magnum binary only
  - id: magnum-archive
    ids:
      - magnum
    formats: binary
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # song-converter binary only
  - id: song-converter-archive
    ids:
      - song-converter
    formats: binary
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # versy binary only
  - id: versy-archive
    ids:
      - versy
    formats: binary
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).